name: ItensEspeciais
main: rush.itensespeciais.Main
author: RUSH
version: 1.1

commands:
  especial:
    description: Giva um item especial para um player.
    aliases: [giveitem]
    permission: itensespecias.admin
    permission-message: "§cVocê não tem permissão para utilizar este comando."